---
- hosts: etcd:master:node:apiserver
  gather_facts: False
  roles:
    - { role: ansible-coreos-bootstrap, coreos_pypy_url: 'https://bitbucket.org/squeaky/portable-pypy/downloads' }

- hosts: node
  gather_facts: False
  roles:
    - { role: socat-coreos-bootstrap, socat_url: 'https://s3-us-west-2.amazonaws.com/sundry-automata/tools/CoreOS/socat/1.7.3.0/x86_64/socat', utils_path: /opt/bin }

- hosts: etcd
  roles:
    - { role: kraken-etcd }

- hosts: master
  roles:
    - { role: kraken-master }

- hosts: node
  roles:
    - { role: kraken-node, utils_path: /opt/bin }

- hosts: apiserver
  roles:
    - { role: kraken-apiserver }